version: '3'

services:
  nginx:
    container_name: blog_nginx
    image: nginx:stable
    ports:
      - ${DOCKER_HTTP_PORT}:80
      - ${DOCKER_HTTPS_PORT}:443
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - mysql

  php:
    container_name: blog_php
    build: ./docker/php
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
      - mysql

  mysql:
    container_name: blog_mysql
    image: mysql:8.0
    restart: always
    ports:
      - ${DOCKER_DB_PORT}:3306
    volumes:
      - mysql-data:/data/mysql/db
    environment:
      MYSQL_DATABASE: ${DOCKER_DB_DATABASE}
      MYSQL_USER: ${DOCKER_DB_USER}
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PASSWORD}

volumes:
  mysql-data:
    driver: local
