<?php

return [
    'accepted' => 'INVALID_MANDATORY_ACCEPT_FIELD',
    'active_url' => 'INVALID_ACTIVE_URL',
    'after' => 'INVALID_DATE_AFTER',
    'after_or_equal' => 'INVALID_DATE_AFTER_OR_EQUAL',
    'alpha' => 'INVALID_ALPHA',
    'alpha_dash' => 'INVALID_ALPHA_DASH',
    'alpha_num' => 'INVALID_ALPHA_NUM',
    'array' => 'INVALID_ARRAY',
    'before' => 'INVALID_DATE_BEFORE',
    'before_or_equal' => 'INVALID_DATE_BEFORE_OR_EQUAL',
    'between' => 'INVALID_RANGE',
    'boolean' => 'INVALID_BOOLEAN',
    'confirmed' => 'INVALID_CONFIRMATION_VALUE',
    'date' => 'INVALID_DATE',
    'date_format' => 'INVALID_DATE_FORMAT',
    'different' => 'INVALID_DIFFERENT_VALUES',
    'digits' => 'INVALID_DIGITS',
    'digits_between' => 'INVALID_DIGITS_RANGE',
    'dimensions' => 'INVALID_IMAGE_DIMENSIONS',
    'distinct' => 'INVALID_DISTINCT_VALUES',
    'email' => 'INVALID_EMAIL',
    'exists' => 'INVALID_EXISTS',
    'file' => 'INVALID_FILE',
    'filled' => 'INVALID_FILLED_VALUE',
    'image' => 'INVALID_IMAGE',
    'in' => 'INVALID_INCLUSION',
    'in_array' => 'INVALID_ARRAY_INCLUSION',
    'integer' => 'INVALID_INTEGER',
    'ip' => 'INVALID_IP',
    'ipv4' => 'INVALID_IPV4',
    'ipv6' => 'INVALID_IPV6',
    'json' => 'INVALID_JSON',
    'max' => 'INVALID_MAX',
    'mimes' => 'INVALID_MIMETYPE',
    'mimetypes' => 'INVALID_MIMETYPE',
    'min' => 'INVALID_MIN',
    'not_in' => 'INVALID_SELECTION',
    'numeric' => 'INVALID_NUMERIC',
    'present' => 'INVALID_FIELD_PRESENT',
    'regex' => 'INVALID_FORMAT',
    'required' => 'INVALID_FIELD_MANDATORY',
    'required_if' => 'INVALID_FIELD_MANDATORY',
    'required_unless' => 'INVALID_FIELD_MANDATORY',
    'required_with' => 'INVALID_FIELD_MANDATORY',
    'required_with_all' => 'INVALID_FIELD_MANDATORY',
    'required_without' => 'INVALID_FIELD_MANDATORY',
    'required_without_all' => 'INVALID_FIELD_MANDATORY',
    'same' => 'INVALID_MATCH',
    'size' => 'INVALID_SIZE',
    'string' => 'INVALID_STRING',
    'timezone' => 'INVALID_TIMEZONE',
    'unique' => 'INVALID_UNIQUE',
    'uploaded' => 'INVALID_UPLOAD',
    'url' => 'INVALID_URL',

    /*
     * Custom
     */
    'not_verified' => 'INVALID_NOT_VERIFIED',

];
